#!/bin/bash

echo "🧪 Running code quality checks using Makefile..."

make quality-check
if [ $? -ne 0 ]; then
  echo "❌ Code quality check failed. Please fix the issues before committing."
  exit 1
fi

echo "✅ All checks passed. Proceeding with commit."
