# =======================================
# deploy.yml - Main branch deploy only
# =======================================
name: Deploy

on:
  push:
    branches: ["main"]

env:
  GCP_REGION: europe-west3
  GCP_PROJECT_ID: openbanking-api-458712
  GCP_SERVICE: openbanking-api
  GCP_REPOSITORY: openbanking-api
  IMAGE_PATH: europe-west3-docker.pkg.dev/openbanking-api-458712/openbanking-api/openbanking-api

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Project
        run: ./gradlew clean bootJar

      - name: Set unique image tag (timestamp + short SHA)
        id: vars
        run: echo "tag=$(date +%s)-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.IMAGE_PATH }}:${{ steps.vars.outputs.tag }} .
          docker push ${{ env.IMAGE_PATH }}:${{ steps.vars.outputs.tag }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_SERVICE }}
          image: ${{ env.IMAGE_PATH }}:${{ steps.vars.outputs.tag }}
          region: ${{ env.GCP_REGION }}

      - name: Allow unauthenticated access
        run: |
          gcloud run services add-iam-policy-binding ${{ env.GCP_SERVICE }} \
            --region=${{ env.GCP_REGION }} \
            --member=allUsers \
            --role=roles/run.invoker

      - name: Deployment Complete
        run: echo "✅ Successfully deployed to Cloud Run -> https://${{ env.GCP_SERVICE }}-${{ secrets.GCP_PROJECT_NUMBER }}.${{ env.GCP_REGION }}.run.app"
