# =======================================
# pr-check.yml - On PR to main only
# =======================================
name: PR Check

on:
  pull_request:
    branches: ["main"]

jobs:
  docker-start:
    name: Validate Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        run: ./gradlew clean build
      - name: Build Docker Image
        run: docker build -t openbanking-api:pr-test .
      - name: Run Docker Container (Smoke Test)
        run: |
            CONTAINER_ID=$(docker run -d -p 8080:8080 openbanking-api:pr-test)
            for i in {1..10}; do
              if curl --fail http://localhost:8080/health; then
                docker stop $CONTAINER_ID
                exit 0
              fi
              sleep 2
            done
            docker logs $CONTAINER_ID
            docker stop $CONTAINER_ID
            echo "❌ Health check failed"
            exit 1

